import type { AxiomTheme } from './types'

export const AXIOM_THEMES = [
  {
    id: 'axiom',
    accent: '#284965',
    accentDark: '#7ea7c4',
    caption: 'FIG. 0.1 - 浑天线刻，经纬定轨。',
    title: '关于「公理」',
    content: '公理——源自希腊语 ἀξίωμα，「被认为值得相信的事物。」宇宙秩序的终极起点，一种无需证明、却维系万物运行的基础真理。 ■',
    captionEn: 'FIG. 0.1 - Celestial rings inscribed; meridians hold their course.',
    titleEn: 'On “Axiom”',
    contentEn: 'Axiom—from Greek axiōma, “that which is considered worthy.” It is the first principle of cosmic order: unproved, yet quietly sustaining the motion of all things. ■',
    illustrationLabel: '浑天仪、旋转地球与轨道星体',
    illustrationLabelEn: 'Armillary sphere, rotating globe and orbital body',
    drawingStatus: 'PLATE TRACING // 天球落笔',
    drawingStatusEn: 'PLATE TRACING // CELESTIAL ORDER',
    ambientStatus: 'FIELD IN MOTION // 经纬自转',
    ambientStatusEn: 'FIELD IN MOTION // WORLD IN ROTATION'
  },
  {
    id: 'singularity',
    accent: '#4A3C59',
    accentDark: '#a997b8',
    caption: 'FIG. 0.2 - 时空曲织，漏斗引流。',
    title: '关于「奇点」',
    content: '奇点——源自拉丁语 singulus，「独一与个体的极致。」所有物理定律在此失效与重启，既是万物的终结，亦是浩瀚起源的开端。 ■',
    captionEn: 'FIG. 0.2 - Spacetime bends; the well gathers every orbit.',
    titleEn: 'On “Singularity”',
    contentEn: 'Singularity—from Latin singulus, “the extreme of the one.” Here physical laws collapse and begin anew: at once the terminus of matter and the threshold of an immense origin. ■',
    illustrationLabel: '弯曲时空网格、重力漏斗与吸积光环',
    illustrationLabelEn: 'Curved spacetime grid, gravity well and accretion disk',
    drawingStatus: 'PLATE TRACING // 引力成形',
    drawingStatusEn: 'PLATE TRACING // GRAVITY WELL',
    ambientStatus: 'FIELD IN MOTION // 光环旋落',
    ambientStatusEn: 'FIELD IN MOTION // ACCRETION FLOW'
  },
  {
    id: 'resonance',
    accent: '#2E5A52',
    accentDark: '#7eb4a8',
    caption: 'FIG. 0.3 - 音叉振波，弦动相合。',
    title: '关于「谐振」',
    content: '谐振——源自拉丁语 resonantia，「回响与反响之韵。」深空天体之间静默而精确的频率呼应，在看似混乱的无垠中结成至美和弦。 ■',
    captionEn: 'FIG. 0.3 - The fork answers; standing waves meet in accord.',
    titleEn: 'On “Resonance”',
    contentEn: 'Resonance—from Latin resonantia, “the cadence of sounding again.” Precise frequencies answer across silent space and resolve the apparent disorder of the infinite into a measured chord. ■',
    illustrationLabel: '古典双音叉、克拉尼驻波与共振节点',
    illustrationLabelEn: 'Classical tuning fork, Chladni standing waves and resonance nodes',
    drawingStatus: 'PLATE TRACING // 声学刻绘',
    drawingStatusEn: 'PLATE TRACING // ACOUSTIC FIGURE',
    ambientStatus: 'FIELD IN MOTION // 同频相合',
    ambientStatusEn: 'FIELD IN MOTION // HARMONIC ACCORD'
  },
  {
    id: 'entropy',
    accent: '#8C5130',
    accentDark: '#cf8961',
    caption: 'FIG. 0.4 - 晶格飞散，归于复杂的必然。',
    title: '关于「熵序」',
    content: '熵序——源自希腊语 ἐντροπία，「内蕴的转变与转向。」当信息越过终极阈值，混沌自发涌现出深层的数理规范，化为不可逆的几何秩序。 ■',
    captionEn: 'FIG. 0.4 - The crystal loosens into irreversible complexity.',
    titleEn: 'On “Entropy”',
    contentEn: 'Entropy—from Greek entropia, “an inward turning or transformation.” Beyond a critical threshold, ordered information disperses into richer forms whose direction cannot simply be reversed. ■',
    illustrationLabel: '六方晶体、蒲公英飞蓬与有机藤丝',
    illustrationLabelEn: 'Hexagonal crystal, drifting dandelion seeds and organic tendrils',
    drawingStatus: 'PLATE TRACING // 晶格析解',
    drawingStatusEn: 'PLATE TRACING // CRYSTAL TRANSITION',
    ambientStatus: 'FIELD IN MOTION // 飞蓬离散',
    ambientStatusEn: 'FIELD IN MOTION // IRREVERSIBLE DRIFT'
  },
  {
    id: 'dimension',
    accent: '#223B47',
    accentDark: '#739aaa',
    caption: 'FIG. 0.5 - 阶梯折叠，超维投影。',
    title: '关于「维向」',
    content: '维向——源自拉丁语 dimensio，「度量与跨越的尺度。」突破观测者的视界局限，在折叠的超方投影中，探寻更高阶空间的存在真实。 ■',
    captionEn: 'FIG. 0.5 - Perspective folds; the higher solid casts its trace.',
    titleEn: 'On “Dimension”',
    contentEn: 'Dimension—from Latin dimensio, “the measure by which one crosses.” Beyond the observer’s horizon, a folded hypercube projection hints at spatial realities inaccessible to a single viewpoint. ■',
    illustrationLabel: '观察眼、透视射线与旋转超立方体',
    illustrationLabelEn: 'Observer eye, perspective rays and rotating tesseract',
    drawingStatus: 'PLATE TRACING // 透视架构',
    drawingStatusEn: 'PLATE TRACING // PROJECTIVE FRAME',
    ambientStatus: 'FIELD IN MOTION // 超方折叠',
    ambientStatusEn: 'FIELD IN MOTION // DIMENSIONAL FOLD'
  },
  {
    id: 'constant',
    accent: '#BA3D32',
    accentDark: '#df786d',
    caption: 'FIG. 0.6 - 螺线寻真，比例永定。',
    title: '关于「常数」',
    content: '常数——源自拉丁语 constans，「坚固与屹立不摇者。」穿越时空的沧海桑田，那些隐藏在星系旋臂与自然底层的、绝不衰减的绝对数值。 ■',
    captionEn: 'FIG. 0.6 - The spiral seeks; the proportion remains.',
    titleEn: 'On “Constant”',
    contentEn: 'Constant—from Latin constans, “that which stands firm.” Across every change of scale and age, absolute relations persist beneath shells, stellar arms and the architecture of nature. ■',
    illustrationLabel: '鹦鹉螺剖面、斐波那契比尺与古典圆规',
    illustrationLabelEn: 'Nautilus section, Fibonacci measure and classical compass',
    drawingStatus: 'PLATE TRACING // 螺壳测绘',
    drawingStatusEn: 'PLATE TRACING // NAUTILUS MEASURE',
    ambientStatus: 'FIELD IN MOTION // 比例恒定',
    ambientStatusEn: 'FIELD IN MOTION // CONSTANT PROPORTION'
  }
] satisfies readonly AxiomTheme[]